name: build and test develop branch
on: 
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ] 
jobs: 
  build-feature:
    runs-on: ubuntu-latest
    steps: 
#########################################################################################################
# 2. descarga el codigo de la rama feature, configura entorno de java y valida si el codigo es compilable  
#########################################################################################################

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: pull and checkout from git repository
      run:
        echo "pulling and checking out from git repository"

    - name: setup java 17
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin' #see 'supported distributions' for availible options'
        java-version: '17'
      
    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with: 
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: 
          ${{ runner.os }}-maven- 

    - name: build with maven
      run: |
          mvn clean test package
          echo "build with maven"}

    # llama analisis Sonar

    - name: trigger Sonar Analisis
      if: success()
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        event-type: sonar-scan-event
        client-payload: '{ "base_branch": "${{ github.base_ref}}" }'

   # llama publish jar

    - name: trigger deploy artifact
      if: success()
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        event-type: publish-artifact-event
        client-payload: '{ "base_branch": "${{ github.base_ref }}" }'